title = "Pier"

[port]
http = 34544
pprof = 34555

[log]
level = "info"
dir = "logs"
filename = "pier.log"
report_caller = false
[log.module]
api_server = "info"
appchain_mgr = "info"
bxh_lite = "info"
executor = "info"
exchanger = "info"
monitor = "info"
peer_mgr = "info"
router = "info"
rule_mgr = "info"
swarm = "info"
syncer = "info"
direct_adapter = "info"
union_adapter = "info"
appchain_adapter = "info"

[mode]
type = "relay" # relay, direct or union
[mode.relay]
addrs = ["localhost:60011"]
timeout_limit = "1s"
quorum = 2
bitxhub_id = "1356"
[mode.direct]
gas_limit = 0x5f5e100

[mode.union]
addrs = ["localhost:60011"]
providers = 1

[security]
enable_tls = false
access_cert = ["node1.cert", "node2.cert", "node3.cert", "node4.cert"]
access_key = "node.priv"
tlsca = "certs/agency.cert"
common_name = "BitXHub"

[HA]
mode = "single"

[appchain]
id = "etherappchain1"
plugin = "eth-client"
config = "ethereum"
