[fabric]
username = "Admin"
ccid = "broker"
channel_id = "mychannel"
org = "org2"
timeout_height = 30
chain_id = "fabricappchain1"

[[services]]
id = "mychannel&transfer"
name = "fabric-transfer-test"

[[services]]
id = "mychannel&data_swapper"
name = "fabric-data-test"