name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Run golanci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: Mushus/golangci-linter@v1

      - name: Go report card
        uses: creekorful/goreportcard-action@v1.0

  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Go build
        run: go build -v ./cmd/premo

